
#--------------------------------------------------------------------------
# Welcome to the AvaIre Role Restore Plugin Configuration
#--------------------------------------------------------------------------
#
#
# Got any questions? Contact the development team on the official support
# server for Ava at https://avairebot.com/support
#

